/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ta_pdkp_atm;

import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
/**
 *
 * @author Kenzie Tama
 */
public class strukWindow extends javax.swing.JFrame {

    /**
     * Creates new form strukWindow
     */
    Properties property = new Properties();
    
    public strukWindow() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
        jPanel3.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        
        labelSisaSaldo1.setVisible(false);
        labelUpdateSaldo1.setVisible(false);
        labelSisaSaldo2.setVisible(false);
        labelUpdateSaldo2.setVisible(false);
        initSettings();
    }
    
    private void initSettings() {
        DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter time = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime current = LocalDateTime.now();
        labelTanggal.setText(date.format(current));
        labelWaktu.setText(time.format(current));
        strukSettings(property.getJenisTransaksi());
        this.setLocationRelativeTo(null);
    }
    
    private void strukSettings(int mode) {
        switch (mode) {
            case 1: {
                labelTransaksi.setText("TARIK TUNAI");
                Line2.setText("Tabungan");
                labelJumlahTransaksi.setText("Rp" + String.format("%,d", property.getJmlPenarikan()));
                labelUpdateSaldo.setText("Rp" + String.format("%,d", property.getSaldo()));
                break;
            }
            case 2: {
                labelTransaksi.setText("SETOR TUNAI");
                labelLine2.setText("SETOR KE :");
                Line2.setText("Tabungan");
                labelLine3.setText("JML UANG :");
                labelJumlahTransaksi.setText("Rp" + String.format("%,d", property.getJmlPenarikan()));
                labelUpdateSaldo.setText("Rp" + String.format("%,d", property.getSaldo()));
                break;
            }
            case 3: {
                labelTransaksi.setText("TRANSFER");
                labelLine2.setText("REK. TUJUAN (" + property.getBankTujuan() + ") :");
                Line2.setText("21120122150000");
                labelLine3.setText("JML TRANSFER :");
                labelJumlahTransaksi.setText("Rp" + String.format("%,d", property.getJmlPenarikan()) + "  B.Admin : Rp" + String.format("%,d", property.getBiayaAdmin()));
                labelUpdateSaldo.setText("Rp" + String.format("%,d", property.getSaldo()));
                break;
            }
            case 4: {
                labelTransaksi.setText("PEMBAYARAN UKT");
                labelRek.setText("INSTITUSI : " + property.getInstitusi());
                labelLine2.setText("NIM :");
                Line2.setText(property.getNIM());
                labelLine3.setText("NAMA :");
                labelJumlahTransaksi.setText("Kenzie Maheswara Tama");
                labelSisaSaldo.setText("SEMESTER :");
                labelUpdateSaldo.setText("Genap-2023");
                labelSisaSaldo1.setText("JUMLAH :");
                labelUpdateSaldo1.setText("Rp6.500.000");
                labelUpdateSaldo2.setText("Rp" + String.format("%,d", property.getSaldo()));
                labelSisaSaldo1.setVisible(true);
                labelSisaSaldo2.setVisible(true);
                labelUpdateSaldo1.setVisible(true);
                labelUpdateSaldo2.setVisible(true);
                break;
            }
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelRek = new javax.swing.JLabel();
        labelLine2 = new javax.swing.JLabel();
        labelLine3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelJumlahTransaksi = new javax.swing.JLabel();
        labelSisaSaldo = new javax.swing.JLabel();
        labelUpdateSaldo = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelTransaksi = new javax.swing.JLabel();
        Line2 = new javax.swing.JLabel();
        labelSisaSaldo1 = new javax.swing.JLabel();
        labelUpdateSaldo1 = new javax.swing.JLabel();
        labelSisaSaldo2 = new javax.swing.JLabel();
        labelUpdateSaldo2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        jPanel1.setFont(new java.awt.Font("Merchant Copy", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel1.setText("BANK TEKKOM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel2.setFont(new java.awt.Font("Merchant Copy", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel2.setText("TANGGAL : ");

        jLabel3.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel3.setText("ATM ID : 211201");

        jLabel4.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel4.setText("LOKASI : 211201-UNDIP");

        jLabel5.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel5.setText("WAKTU :");

        jLabel6.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel6.setText("NO. REF : 123456");

        labelRek.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelRek.setText("NO. REKENING : 21120122130046");

        labelLine2.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelLine2.setText("SUMBER DANA :");

        labelLine3.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelLine3.setText("JML PENARIKAN :");

        jLabel11.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        jLabel11.setText("TERIMAKASIH MENGGUNAKAN ATM TEKKOM");

        labelJumlahTransaksi.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelJumlahTransaksi.setText("jLabel12");

        labelSisaSaldo.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelSisaSaldo.setText("SISA SALDO : ");

        labelUpdateSaldo.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelUpdateSaldo.setText("jLabel14");

        labelTanggal.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelTanggal.setText("jLabel7");

        labelWaktu.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelWaktu.setText("jLabel12");

        labelTransaksi.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelTransaksi.setText("jLabel7");
        labelTransaksi.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelTransaksi)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Line2.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        Line2.setText("jLabel7");

        labelSisaSaldo1.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelSisaSaldo1.setText("SISA SALDO : ");

        labelUpdateSaldo1.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelUpdateSaldo1.setText("jLabel14");

        labelSisaSaldo2.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelSisaSaldo2.setText("SISA SALDO : ");

        labelUpdateSaldo2.setFont(new java.awt.Font("Merchant Copy", 0, 24)); // NOI18N
        labelUpdateSaldo2.setText("jLabel14");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelTanggal)))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelWaktu))
                                    .addComponent(jLabel6))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelSisaSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUpdateSaldo))
                    .addComponent(labelRek)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLine2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Line2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelLine3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJumlahTransaksi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelSisaSaldo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUpdateSaldo1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelSisaSaldo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUpdateSaldo2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(labelTanggal)
                    .addComponent(labelWaktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelRek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLine2)
                    .addComponent(Line2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLine3)
                    .addComponent(labelJumlahTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSisaSaldo)
                    .addComponent(labelUpdateSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSisaSaldo1)
                    .addComponent(labelUpdateSaldo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSisaSaldo2)
                    .addComponent(labelUpdateSaldo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(17, 17, 17))
        );

        jPanel3.setFont(new java.awt.Font("Merchant Copy", 0, 12)); // NOI18N

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton3)
                .addGap(141, 141, 141)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3)
                .addComponent(jButton4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new nextWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(strukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(strukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(strukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(strukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new strukWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Line2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelJumlahTransaksi;
    private javax.swing.JLabel labelLine2;
    private javax.swing.JLabel labelLine3;
    private javax.swing.JLabel labelRek;
    private javax.swing.JLabel labelSisaSaldo;
    private javax.swing.JLabel labelSisaSaldo1;
    private javax.swing.JLabel labelSisaSaldo2;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JLabel labelUpdateSaldo;
    private javax.swing.JLabel labelUpdateSaldo1;
    private javax.swing.JLabel labelUpdateSaldo2;
    private javax.swing.JLabel labelWaktu;
    // End of variables declaration//GEN-END:variables
}
